### ISSUE TITLE
Set up automated builds and releases

### ISSUE THREAD

**Issue by Bemoliph** [Bemoliph/lakeception#6]
Lakeception needs automated builds and releases for two reasons:

 * It's hard to install and play, especially on Windows due to PyGame.
 * Automated tests, maybe, some day.

Travis CI is a hosted solution that's free for open source projects, so that's probably a good bet.

**Comment by Bemoliph** [comment]
Ended up using Appveyor for Windows builds, but this is working as of 6a46696

Project is automatically built and released with each tag.  Automated testing each commit regardless of tag might need extra config.

**Comment by cblgh** [comment]
👏 👮
